### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by higaski** [GeekyAnts/GaugesFlutter#286]
Would it be possible to give users the option to not depend on the `Roboto-Regular.ttf` font?

Currently it looks like the font gets always added through the pubspec file.

```yml
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
```
